=== Luca-Guerra/app-serv-web/web/xml-types/accounts.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="accounts">
<xs:complexType>
<xs:sequence>
<xs:element name="account" maxOccurs="unbounded" minOccurs="0">
    <xs:complexType>
    <xs:sequence>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="surname"/>
        <xs:element type="xs:string" name="username"/>
        <xs:element name="password">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="4"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="role"> 
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="patient|doctor"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:sequence>
            <xs:choice>
                <xs:element name="doctor" type="doctorType"></xs:element>
                <xs:element name="patients" type="patientsType"></xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="doctorType">
    <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="lastVisit" type="xs:positiveInteger"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="patientsType">
    <xs:sequence>
        <xs:element name="patient" type="patientType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="patientType">
    <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="lastVisit" type="xs:positiveInteger"/>
    </xs:sequence>
</xs:complexType>
</xs:schema>

=== Luca-Guerra/app-serv-web/web/WEB-INF/xml/accounts.xml
<?xml version="1.0"?>
<accounts
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../xml-types/accounts.xsd">
  <account>
    <name>Luca</name>
    <surname>Guerra</surname>
    <username>luca</username>
    <password>123456</password>
    <role>doctor</role>
    <patients>
        <patient>
            <name>marco</name>
            <lastVisit>1</lastVisit>
        </patient>
        <patient>
            <name>fabio</name>
            <lastVisit>2</lastVisit>
        </patient>
        <patient>
            <name>riccardo</name>
            <lastVisit>3</lastVisit>
        </patient>
    </patients>
  </account>
  <account>
    <name>Marco</name>
    <surname>Franceschini</surname>
    <username>marco</username>
    <password>123456</password>
    <role>patient</role>
    <doctor>
        <name>luca</name>
        <lastVisit>3</lastVisit>
    </doctor>
  </account>
  <account>
    <name>Fabio</name>
    <surname>Consalici</surname>
    <username>fabio</username>
    <password>123456</password>
    <role>patient</role>
    <doctor>
        <name>luca</name>
        <lastVisit>3</lastVisit>
    </doctor>
  </account>
  <account>
    <name>Riccardo</name>
    <surname>Drudi</surname>
    <username>riccardo</username>
    <password>123456</password>
    <role>patient</role>
    <doctor>
        <name>luca</name>
        <lastVisit>3</lastVisit>
    </doctor>
  </account>
</accounts>
