=== Luca-Guerra/app-serv-web/web/xml-types/agenda.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="agenda">
<xs:complexType>
<xs:sequence>
<xs:element name="appointment" maxOccurs="unbounded" minOccurs="0">
    <xs:complexType>
    <xs:sequence>
        <xs:element type="xs:string" name="date"/>
        <xs:element type="xs:boolean" name="available"/>
        <xs:element type="xs:string" name="patient"/>
        <xs:element name="slot">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Luca-Guerra/app-serv-web/web/WEB-INF/xml/agenda/luca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../../xml-types/agenda.xsd">
    <appointment>
        <date>01/6/2015</date>
        <available>true</available>
        <patient>marco</patient>
        <slot>0</slot>
    </appointment>
    <appointment>
        <date>01/6/2015</date>
        <available>true</available>
        <patient>marco</patient>
        <slot>1</slot>
    </appointment>
    <appointment>
        <date>01/6/2015</date>
        <available>false</available>
        <patient/>
        <slot>2</slot>
    </appointment>
</agenda>
