=== Luca-Guerra/app-serv-web/web/xml-types/conversation.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="messages">
<xs:complexType>
<xs:sequence>
<xs:element name="message" maxOccurs="unbounded" minOccurs="0">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="sender"> 
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="patient|doctor"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="receiver"> 
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="patient|doctor"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="type"> 
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="text|img|doc"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element type="xs:string" name="text"/>
        <xs:element type="xs:string" name="dateTime"/>
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Luca-Guerra/app-serv-web/web/WEB-INF/xml/conversation/fabio.xml
<?xml version="1.0"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../../xml-types/conversation.xsd">
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Salve dottore come va?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Salve tutto bene lei?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>    
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Non saprei ho una accetta piantata in testa cosa mi consiglia?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Lascia l'ascia ma accetta l'accetta!</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Salve dottore come va?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Salve tutto bene lei?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Non saprei ho una accetta piantata in testa cosa mi consiglia?Non saprei ho una accetta piantata in testa cosa mi consiglia?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Lascia l'ascia ma accetta l'accetta!</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Salve dottore come va?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Salve tutto bene lei?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>    
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Non saprei ho una accetta piantata in testa cosa mi consiglia?Non saprei ho una accetta piantata in testa cosa mi consiglia?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Lascia l'ascia ma accetta l'accetta!</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Salve dottore come va?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Salve tutto bene lei?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>patient</sender>
        <receiver>doctor</receiver>
        <type>text</type>
        <text>Non saprei ho una accetta piantata in testa cosa mi consiglia?Non saprei ho una accetta piantata in testa cosa mi consiglia?</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
    <message>
        <sender>doctor</sender>
        <receiver>patient</receiver>
        <type>text</type>
        <text>Lascia l'ascia ma accetta l'accetta!</text>
        <dateTime>Mon Jun 01 10:54:00 CEST 2015</dateTime>
    </message>
</messages>
